lorena.token=${DISCORD_TOKEN}
net.freecurrencyapi.token=${CURRENCY_API_TOKEN}
spring.mongodb.uri=mongodb+srv://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}?retryWrites=true&w=majority
spring.mongodb.database=${DATABASE_NAME}
server.port=${PORT}

